void bubblesort(int arr[], int n);
void printarray(int arr[], int n);
void swap(int *a, int *b);
void insertionsort(int arr[], int n);
void selectionsort(int arr[], int n);
void mergesort(int arr[], int beg, int end);
void quicksort(int arr[], int beg, int end);
void countingsort(int arr[], int n);
void radixsort(int arr[], int n);
void shellsort(int arr[], int n);
void heapsort(int arr[], int n);
